### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by sylv256** [FukkitMC/fukkit-repo#1]
The name is very inappropriate. I wouldn't speak of this library anywhere in the Fabric community without getting at least a 24 hour mute. Please change the name.

**Comment by TwilightFlower** [comment]
where in the fabric community would you get muted for saying "fuck" lmao

**Comment by hYdos** [comment]
i have mentioned it multiple times. im not sure what you are talking about

**Comment by Ueaj-Kerman** [comment]
no

**Comment by hYdos** [comment]
nice

**Comment by eatmyvenom** [comment]
He got fukkd
